apiVersion: v1
kind: ConfigMap
metadata:
  name: configuration-application
data:
  POSTGRES_HOST: db
  POSTGRES_PORT: "5432"
  POSTGRES_USER: postgres
  POSTGRES_DATABASE: mabase
  API_HOST: "0.0.0.0"
  API_PORT: "8000"